### ISSUE TITLE
Fetch events created by the user(or body) and display in My events fragment

### ISSUE THREAD

**Issue by unstablebrainiac** [wncc/InstiApp#50]

**Comment by pulsejet** [comment]
* `api/bodies/{uuid}`  returns events with the body details.
* `api/user-me/events` returns events created by the user.

**Comment by unstablebrainiac** [comment]
We need a single endpoint that returns these all of these lists. Having multiple network requests for this will make the app slow.

**Comment by pulsejet** [comment]
There are just two requests. Should be fast enough

**Comment by unstablebrainiac** [comment]
It's still good practice to do the processing in the backend. The frontend should only be responsible for fetching and displaying data as far as possible.

**Comment by pulsejet** [comment]
Yes, but at the same time, we shouldn't have endpoints returning data with mixed contexts, since they are hard to maintain. This is applicable here because the roles of the user has nothing to do with the events they have created, so we will need a wrapper around the two arrays, and then one array will have `Role` objects and the other `Event`, so it all gets a bit weird. Also, this will reduce the client's flexibility far too much IMO.
